# Generated by Django 4.2.3 on 2024-04-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='dtEntrega',
            new_name='data_entrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='endrNtrg',
            new_name='endereco_entrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='nmClnt',
            new_name='nome_cliente',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='nmeFrt',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='prcFrt',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='qntdDspnvl',
            new_name='quantidade_disponivel',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nmItm',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='prcUnit',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='qntdd',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='mtPgto',
            new_name='metodo_pagamento',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='vlrTotal',
            new_name='valor_total',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='stkVxL',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='nmVdx',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='pXcVdX',
            new_name='preco_por_quilo',
        ),
    ]
